# environment for running the provided notebooks

name: vault
channels:
  - pyviz/label/dev
  - defaults
dependencies:
  - bokeh ==2.2.3
  - colorcet ==2
  - dask ==2020.12.0
  - datashader ==0.12.0rc1
  - h5py ==2.10.0
  - hdf5 ==1.10.4
  - holoviews ==1.14.0
  - matplotlib ==3.3.2
  - notebook ==6.1.5
  - numba ==0.51.2
  - numexpr ==2.7.1
  - pandas ==1.1.5
  - python ==3.7.9
  - pytables ==3.6.1
  - scipy ==1.5.2
  - six ==1.15.0
  - spatialpandas ==0.3.6
  - xarray ==0.16.2
  - pip ==20.3.3
  - pip:
    - skyfield ==1.34
    - sgp4 ==2.14
